/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PetshopRouteImport } from './routes/petshop'
import { Route as ModaRouteImport } from './routes/moda'
import { Route as ManualImpressaoRouteImport } from './routes/manual-impressao'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HofRouteImport } from './routes/hof'
import { Route as FoodServiceRouteImport } from './routes/food-service'
import { Route as EsteticaRouteImport } from './routes/estetica'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as EscolherPerfilRouteImport } from './routes/escolher-perfil'
import { Route as EscolherAreaRouteImport } from './routes/escolher-area'
import { Route as EmailConfirmadoRouteImport } from './routes/email-confirmado'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedIncidentesRouteImport } from './routes/_authenticated/incidentes'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAcompanhamentoRouteImport } from './routes/_authenticated/acompanhamento'
import { Route as ApiPublicCronArchiveRouteImport } from './routes/api/public/cron-archive'
import { Route as AuthenticatedAdminAlunoEnrollmentIdRouteImport } from './routes/_authenticated/admin.aluno.$enrollmentId'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PetshopRoute = PetshopRouteImport.update({
  id: '/petshop',
  path: '/petshop',
  getParentRoute: () => rootRouteImport,
} as any)
const ModaRoute = ModaRouteImport.update({
  id: '/moda',
  path: '/moda',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualImpressaoRoute = ManualImpressaoRouteImport.update({
  id: '/manual-impressao',
  path: '/manual-impressao',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HofRoute = HofRouteImport.update({
  id: '/hof',
  path: '/hof',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodServiceRoute = FoodServiceRouteImport.update({
  id: '/food-service',
  path: '/food-service',
  getParentRoute: () => rootRouteImport,
} as any)
const EsteticaRoute = EsteticaRouteImport.update({
  id: '/estetica',
  path: '/estetica',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const EscolherPerfilRoute = EscolherPerfilRouteImport.update({
  id: '/escolher-perfil',
  path: '/escolher-perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const EscolherAreaRoute = EscolherAreaRouteImport.update({
  id: '/escolher-area',
  path: '/escolher-area',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailConfirmadoRoute = EmailConfirmadoRouteImport.update({
  id: '/email-confirmado',
  path: '/email-confirmado',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIncidentesRoute = AuthenticatedIncidentesRouteImport.update({
  id: '/incidentes',
  path: '/incidentes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAcompanhamentoRoute =
  AuthenticatedAcompanhamentoRouteImport.update({
    id: '/acompanhamento',
    path: '/acompanhamento',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicCronArchiveRoute = ApiPublicCronArchiveRouteImport.update({
  id: '/api/public/cron-archive',
  path: '/api/public/cron-archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAlunoEnrollmentIdRoute =
  AuthenticatedAdminAlunoEnrollmentIdRouteImport.update({
    id: '/aluno/$enrollmentId',
    path: '/aluno/$enrollmentId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/email-confirmado': typeof EmailConfirmadoRoute
  '/escolher-area': typeof EscolherAreaRoute
  '/escolher-perfil': typeof EscolherPerfilRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/estetica': typeof EsteticaRoute
  '/food-service': typeof FoodServiceRoute
  '/hof': typeof HofRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/manual-impressao': typeof ManualImpressaoRoute
  '/moda': typeof ModaRoute
  '/petshop': typeof PetshopRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/acompanhamento': typeof AuthenticatedAcompanhamentoRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/incidentes': typeof AuthenticatedIncidentesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/api/public/cron-archive': typeof ApiPublicCronArchiveRoute
  '/admin/aluno/$enrollmentId': typeof AuthenticatedAdminAlunoEnrollmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/email-confirmado': typeof EmailConfirmadoRoute
  '/escolher-area': typeof EscolherAreaRoute
  '/escolher-perfil': typeof EscolherPerfilRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/estetica': typeof EsteticaRoute
  '/food-service': typeof FoodServiceRoute
  '/hof': typeof HofRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/manual-impressao': typeof ManualImpressaoRoute
  '/moda': typeof ModaRoute
  '/petshop': typeof PetshopRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/acompanhamento': typeof AuthenticatedAcompanhamentoRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/incidentes': typeof AuthenticatedIncidentesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/api/public/cron-archive': typeof ApiPublicCronArchiveRoute
  '/admin/aluno/$enrollmentId': typeof AuthenticatedAdminAlunoEnrollmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/email-confirmado': typeof EmailConfirmadoRoute
  '/escolher-area': typeof EscolherAreaRoute
  '/escolher-perfil': typeof EscolherPerfilRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/estetica': typeof EsteticaRoute
  '/food-service': typeof FoodServiceRoute
  '/hof': typeof HofRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/manual-impressao': typeof ManualImpressaoRoute
  '/moda': typeof ModaRoute
  '/petshop': typeof PetshopRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/_authenticated/acompanhamento': typeof AuthenticatedAcompanhamentoRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/incidentes': typeof AuthenticatedIncidentesRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/api/public/cron-archive': typeof ApiPublicCronArchiveRoute
  '/_authenticated/admin/aluno/$enrollmentId': typeof AuthenticatedAdminAlunoEnrollmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/email-confirmado'
    | '/escolher-area'
    | '/escolher-perfil'
    | '/esqueci-senha'
    | '/estetica'
    | '/food-service'
    | '/hof'
    | '/login'
    | '/manual'
    | '/manual-impressao'
    | '/moda'
    | '/petshop'
    | '/privacidade'
    | '/redefinir-senha'
    | '/signup'
    | '/sitemap.xml'
    | '/termos'
    | '/acompanhamento'
    | '/admin'
    | '/dashboard'
    | '/documentos'
    | '/incidentes'
    | '/perfil'
    | '/tarefas'
    | '/api/public/cron-archive'
    | '/admin/aluno/$enrollmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/email-confirmado'
    | '/escolher-area'
    | '/escolher-perfil'
    | '/esqueci-senha'
    | '/estetica'
    | '/food-service'
    | '/hof'
    | '/login'
    | '/manual'
    | '/manual-impressao'
    | '/moda'
    | '/petshop'
    | '/privacidade'
    | '/redefinir-senha'
    | '/signup'
    | '/sitemap.xml'
    | '/termos'
    | '/acompanhamento'
    | '/admin'
    | '/dashboard'
    | '/documentos'
    | '/incidentes'
    | '/perfil'
    | '/tarefas'
    | '/api/public/cron-archive'
    | '/admin/aluno/$enrollmentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/email-confirmado'
    | '/escolher-area'
    | '/escolher-perfil'
    | '/esqueci-senha'
    | '/estetica'
    | '/food-service'
    | '/hof'
    | '/login'
    | '/manual'
    | '/manual-impressao'
    | '/moda'
    | '/petshop'
    | '/privacidade'
    | '/redefinir-senha'
    | '/signup'
    | '/sitemap.xml'
    | '/termos'
    | '/_authenticated/acompanhamento'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/documentos'
    | '/_authenticated/incidentes'
    | '/_authenticated/perfil'
    | '/_authenticated/tarefas'
    | '/api/public/cron-archive'
    | '/_authenticated/admin/aluno/$enrollmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  EmailConfirmadoRoute: typeof EmailConfirmadoRoute
  EscolherAreaRoute: typeof EscolherAreaRoute
  EscolherPerfilRoute: typeof EscolherPerfilRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  EsteticaRoute: typeof EsteticaRoute
  FoodServiceRoute: typeof FoodServiceRoute
  HofRoute: typeof HofRoute
  LoginRoute: typeof LoginRoute
  ManualRoute: typeof ManualRoute
  ManualImpressaoRoute: typeof ManualImpressaoRoute
  ModaRoute: typeof ModaRoute
  PetshopRoute: typeof PetshopRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosRoute: typeof TermosRoute
  ApiPublicCronArchiveRoute: typeof ApiPublicCronArchiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petshop': {
      id: '/petshop'
      path: '/petshop'
      fullPath: '/petshop'
      preLoaderRoute: typeof PetshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moda': {
      id: '/moda'
      path: '/moda'
      fullPath: '/moda'
      preLoaderRoute: typeof ModaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual-impressao': {
      id: '/manual-impressao'
      path: '/manual-impressao'
      fullPath: '/manual-impressao'
      preLoaderRoute: typeof ManualImpressaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hof': {
      id: '/hof'
      path: '/hof'
      fullPath: '/hof'
      preLoaderRoute: typeof HofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food-service': {
      id: '/food-service'
      path: '/food-service'
      fullPath: '/food-service'
      preLoaderRoute: typeof FoodServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estetica': {
      id: '/estetica'
      path: '/estetica'
      fullPath: '/estetica'
      preLoaderRoute: typeof EsteticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escolher-perfil': {
      id: '/escolher-perfil'
      path: '/escolher-perfil'
      fullPath: '/escolher-perfil'
      preLoaderRoute: typeof EscolherPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escolher-area': {
      id: '/escolher-area'
      path: '/escolher-area'
      fullPath: '/escolher-area'
      preLoaderRoute: typeof EscolherAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-confirmado': {
      id: '/email-confirmado'
      path: '/email-confirmado'
      fullPath: '/email-confirmado'
      preLoaderRoute: typeof EmailConfirmadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incidentes': {
      id: '/_authenticated/incidentes'
      path: '/incidentes'
      fullPath: '/incidentes'
      preLoaderRoute: typeof AuthenticatedIncidentesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/acompanhamento': {
      id: '/_authenticated/acompanhamento'
      path: '/acompanhamento'
      fullPath: '/acompanhamento'
      preLoaderRoute: typeof AuthenticatedAcompanhamentoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/cron-archive': {
      id: '/api/public/cron-archive'
      path: '/api/public/cron-archive'
      fullPath: '/api/public/cron-archive'
      preLoaderRoute: typeof ApiPublicCronArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/aluno/$enrollmentId': {
      id: '/_authenticated/admin/aluno/$enrollmentId'
      path: '/aluno/$enrollmentId'
      fullPath: '/admin/aluno/$enrollmentId'
      preLoaderRoute: typeof AuthenticatedAdminAlunoEnrollmentIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAlunoEnrollmentIdRoute: typeof AuthenticatedAdminAlunoEnrollmentIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAlunoEnrollmentIdRoute:
    AuthenticatedAdminAlunoEnrollmentIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAcompanhamentoRoute: typeof AuthenticatedAcompanhamentoRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedIncidentesRoute: typeof AuthenticatedIncidentesRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAcompanhamentoRoute: AuthenticatedAcompanhamentoRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedIncidentesRoute: AuthenticatedIncidentesRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  EmailConfirmadoRoute: EmailConfirmadoRoute,
  EscolherAreaRoute: EscolherAreaRoute,
  EscolherPerfilRoute: EscolherPerfilRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  EsteticaRoute: EsteticaRoute,
  FoodServiceRoute: FoodServiceRoute,
  HofRoute: HofRoute,
  LoginRoute: LoginRoute,
  ManualRoute: ManualRoute,
  ManualImpressaoRoute: ManualImpressaoRoute,
  ModaRoute: ModaRoute,
  PetshopRoute: PetshopRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosRoute: TermosRoute,
  ApiPublicCronArchiveRoute: ApiPublicCronArchiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
