/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ModaRouteImport } from './routes/moda'
import { Route as ManualImpressaoRouteImport } from './routes/manual-impressao'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HofRouteImport } from './routes/hof'
import { Route as FoodServiceRouteImport } from './routes/food-service'
import { Route as EsteticaRouteImport } from './routes/estetica'
import { Route as EscolherPerfilRouteImport } from './routes/escolher-perfil'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as AuthenticatedIncidentesRouteImport } from './routes/_authenticated/incidentes'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAcompanhamentoRouteImport } from './routes/_authenticated/acompanhamento'
import { Route as ApiPublicCronArchiveRouteImport } from './routes/api/public/cron-archive'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ModaRoute = ModaRouteImport.update({
  id: '/moda',
  path: '/moda',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualImpressaoRoute = ManualImpressaoRouteImport.update({
  id: '/manual-impressao',
  path: '/manual-impressao',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HofRoute = HofRouteImport.update({
  id: '/hof',
  path: '/hof',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodServiceRoute = FoodServiceRouteImport.update({
  id: '/food-service',
  path: '/food-service',
  getParentRoute: () => rootRouteImport,
} as any)
const EsteticaRoute = EsteticaRouteImport.update({
  id: '/estetica',
  path: '/estetica',
  getParentRoute: () => rootRouteImport,
} as any)
const EscolherPerfilRoute = EscolherPerfilRouteImport.update({
  id: '/escolher-perfil',
  path: '/escolher-perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIncidentesRoute = AuthenticatedIncidentesRouteImport.update({
  id: '/incidentes',
  path: '/incidentes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAcompanhamentoRoute =
  AuthenticatedAcompanhamentoRouteImport.update({
    id: '/acompanhamento',
    path: '/acompanhamento',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicCronArchiveRoute = ApiPublicCronArchiveRouteImport.update({
  id: '/api/public/cron-archive',
  path: '/api/public/cron-archive',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/escolher-perfil': typeof EscolherPerfilRoute
  '/estetica': typeof EsteticaRoute
  '/food-service': typeof FoodServiceRoute
  '/hof': typeof HofRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/manual-impressao': typeof ManualImpressaoRoute
  '/moda': typeof ModaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/acompanhamento': typeof AuthenticatedAcompanhamentoRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/incidentes': typeof AuthenticatedIncidentesRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/api/public/cron-archive': typeof ApiPublicCronArchiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/escolher-perfil': typeof EscolherPerfilRoute
  '/estetica': typeof EsteticaRoute
  '/food-service': typeof FoodServiceRoute
  '/hof': typeof HofRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/manual-impressao': typeof ManualImpressaoRoute
  '/moda': typeof ModaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/acompanhamento': typeof AuthenticatedAcompanhamentoRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/incidentes': typeof AuthenticatedIncidentesRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/api/public/cron-archive': typeof ApiPublicCronArchiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/escolher-perfil': typeof EscolherPerfilRoute
  '/estetica': typeof EsteticaRoute
  '/food-service': typeof FoodServiceRoute
  '/hof': typeof HofRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/manual-impressao': typeof ManualImpressaoRoute
  '/moda': typeof ModaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/_authenticated/acompanhamento': typeof AuthenticatedAcompanhamentoRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/incidentes': typeof AuthenticatedIncidentesRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/api/public/cron-archive': typeof ApiPublicCronArchiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/escolher-perfil'
    | '/estetica'
    | '/food-service'
    | '/hof'
    | '/login'
    | '/manual'
    | '/manual-impressao'
    | '/moda'
    | '/privacidade'
    | '/signup'
    | '/termos'
    | '/acompanhamento'
    | '/admin'
    | '/dashboard'
    | '/documentos'
    | '/incidentes'
    | '/tarefas'
    | '/api/public/cron-archive'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/escolher-perfil'
    | '/estetica'
    | '/food-service'
    | '/hof'
    | '/login'
    | '/manual'
    | '/manual-impressao'
    | '/moda'
    | '/privacidade'
    | '/signup'
    | '/termos'
    | '/acompanhamento'
    | '/admin'
    | '/dashboard'
    | '/documentos'
    | '/incidentes'
    | '/tarefas'
    | '/api/public/cron-archive'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/escolher-perfil'
    | '/estetica'
    | '/food-service'
    | '/hof'
    | '/login'
    | '/manual'
    | '/manual-impressao'
    | '/moda'
    | '/privacidade'
    | '/signup'
    | '/termos'
    | '/_authenticated/acompanhamento'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/documentos'
    | '/_authenticated/incidentes'
    | '/_authenticated/tarefas'
    | '/api/public/cron-archive'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  EscolherPerfilRoute: typeof EscolherPerfilRoute
  EsteticaRoute: typeof EsteticaRoute
  FoodServiceRoute: typeof FoodServiceRoute
  HofRoute: typeof HofRoute
  LoginRoute: typeof LoginRoute
  ManualRoute: typeof ManualRoute
  ManualImpressaoRoute: typeof ManualImpressaoRoute
  ModaRoute: typeof ModaRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SignupRoute: typeof SignupRoute
  TermosRoute: typeof TermosRoute
  ApiPublicCronArchiveRoute: typeof ApiPublicCronArchiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moda': {
      id: '/moda'
      path: '/moda'
      fullPath: '/moda'
      preLoaderRoute: typeof ModaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual-impressao': {
      id: '/manual-impressao'
      path: '/manual-impressao'
      fullPath: '/manual-impressao'
      preLoaderRoute: typeof ManualImpressaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hof': {
      id: '/hof'
      path: '/hof'
      fullPath: '/hof'
      preLoaderRoute: typeof HofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food-service': {
      id: '/food-service'
      path: '/food-service'
      fullPath: '/food-service'
      preLoaderRoute: typeof FoodServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estetica': {
      id: '/estetica'
      path: '/estetica'
      fullPath: '/estetica'
      preLoaderRoute: typeof EsteticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escolher-perfil': {
      id: '/escolher-perfil'
      path: '/escolher-perfil'
      fullPath: '/escolher-perfil'
      preLoaderRoute: typeof EscolherPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incidentes': {
      id: '/_authenticated/incidentes'
      path: '/incidentes'
      fullPath: '/incidentes'
      preLoaderRoute: typeof AuthenticatedIncidentesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/acompanhamento': {
      id: '/_authenticated/acompanhamento'
      path: '/acompanhamento'
      fullPath: '/acompanhamento'
      preLoaderRoute: typeof AuthenticatedAcompanhamentoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/cron-archive': {
      id: '/api/public/cron-archive'
      path: '/api/public/cron-archive'
      fullPath: '/api/public/cron-archive'
      preLoaderRoute: typeof ApiPublicCronArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAcompanhamentoRoute: typeof AuthenticatedAcompanhamentoRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedIncidentesRoute: typeof AuthenticatedIncidentesRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAcompanhamentoRoute: AuthenticatedAcompanhamentoRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedIncidentesRoute: AuthenticatedIncidentesRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  EscolherPerfilRoute: EscolherPerfilRoute,
  EsteticaRoute: EsteticaRoute,
  FoodServiceRoute: FoodServiceRoute,
  HofRoute: HofRoute,
  LoginRoute: LoginRoute,
  ManualRoute: ManualRoute,
  ManualImpressaoRoute: ManualImpressaoRoute,
  ModaRoute: ModaRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SignupRoute: SignupRoute,
  TermosRoute: TermosRoute,
  ApiPublicCronArchiveRoute: ApiPublicCronArchiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
