/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ModaRouteImport } from './routes/moda'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HofRouteImport } from './routes/hof'
import { Route as FoodServiceRouteImport } from './routes/food-service'
import { Route as EsteticaRouteImport } from './routes/estetica'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedIncidentesRouteImport } from './routes/_authenticated/incidentes'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ModaRoute = ModaRouteImport.update({
  id: '/moda',
  path: '/moda',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HofRoute = HofRouteImport.update({
  id: '/hof',
  path: '/hof',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodServiceRoute = FoodServiceRouteImport.update({
  id: '/food-service',
  path: '/food-service',
  getParentRoute: () => rootRouteImport,
} as any)
const EsteticaRoute = EsteticaRouteImport.update({
  id: '/estetica',
  path: '/estetica',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIncidentesRoute = AuthenticatedIncidentesRouteImport.update({
  id: '/incidentes',
  path: '/incidentes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/estetica': typeof EsteticaRoute
  '/food-service': typeof FoodServiceRoute
  '/hof': typeof HofRoute
  '/login': typeof LoginRoute
  '/moda': typeof ModaRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/incidentes': typeof AuthenticatedIncidentesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/estetica': typeof EsteticaRoute
  '/food-service': typeof FoodServiceRoute
  '/hof': typeof HofRoute
  '/login': typeof LoginRoute
  '/moda': typeof ModaRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/incidentes': typeof AuthenticatedIncidentesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/estetica': typeof EsteticaRoute
  '/food-service': typeof FoodServiceRoute
  '/hof': typeof HofRoute
  '/login': typeof LoginRoute
  '/moda': typeof ModaRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/incidentes': typeof AuthenticatedIncidentesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/estetica'
    | '/food-service'
    | '/hof'
    | '/login'
    | '/moda'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/documentos'
    | '/incidentes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/estetica'
    | '/food-service'
    | '/hof'
    | '/login'
    | '/moda'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/documentos'
    | '/incidentes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/estetica'
    | '/food-service'
    | '/hof'
    | '/login'
    | '/moda'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/documentos'
    | '/_authenticated/incidentes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  EsteticaRoute: typeof EsteticaRoute
  FoodServiceRoute: typeof FoodServiceRoute
  HofRoute: typeof HofRoute
  LoginRoute: typeof LoginRoute
  ModaRoute: typeof ModaRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moda': {
      id: '/moda'
      path: '/moda'
      fullPath: '/moda'
      preLoaderRoute: typeof ModaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hof': {
      id: '/hof'
      path: '/hof'
      fullPath: '/hof'
      preLoaderRoute: typeof HofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food-service': {
      id: '/food-service'
      path: '/food-service'
      fullPath: '/food-service'
      preLoaderRoute: typeof FoodServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estetica': {
      id: '/estetica'
      path: '/estetica'
      fullPath: '/estetica'
      preLoaderRoute: typeof EsteticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/incidentes': {
      id: '/_authenticated/incidentes'
      path: '/incidentes'
      fullPath: '/incidentes'
      preLoaderRoute: typeof AuthenticatedIncidentesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedIncidentesRoute: typeof AuthenticatedIncidentesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedIncidentesRoute: AuthenticatedIncidentesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  EsteticaRoute: EsteticaRoute,
  FoodServiceRoute: FoodServiceRoute,
  HofRoute: HofRoute,
  LoginRoute: LoginRoute,
  ModaRoute: ModaRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
